"""added health metrices to health diary table

Revision ID: 81dda835705a
Revises: e7c89f7a0327
Create Date: 2025-05-21 20:58:53.367549

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81dda835705a'
down_revision: Union[str, None] = 'e7c89f7a0327'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('health_diary', sa.Column('health_metrics', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('health_diary', 'health_metrics')
    # ### end Alembic commands ###
