"""update_national_database_connection

Revision ID: 8b181a5d47f9
Revises: 0709237098a3
Create Date: 2025-05-27 00:04:12.640885

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8b181a5d47f9'
down_revision: Union[str, None] = '0709237098a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('national_database_connections', sa.Column('provider_id', sa.Integer(), nullable=False))
    op.add_column('national_database_connections', sa.Column('encrypted_credentials', sa.JSON(), nullable=False))
    op.add_column('national_database_connections', sa.Column('credential_hash', sa.String(), nullable=False))
    op.add_column('national_database_connections', sa.Column('last_verified', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'national_database_connections', 'users', ['provider_id'], ['id'])
    op.drop_column('national_database_connections', 'refresh_token')
    op.drop_column('national_database_connections', 'connection_config')
    op.drop_column('national_database_connections', 'token_expires_at')
    op.drop_column('national_database_connections', 'access_token')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('national_database_connections', sa.Column('access_token', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('national_database_connections', sa.Column('token_expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('national_database_connections', sa.Column('connection_config', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('national_database_connections', sa.Column('refresh_token', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'national_database_connections', type_='foreignkey')
    op.drop_column('national_database_connections', 'last_verified')
    op.drop_column('national_database_connections', 'credential_hash')
    op.drop_column('national_database_connections', 'encrypted_credentials')
    op.drop_column('national_database_connections', 'provider_id')
    # ### end Alembic commands ###
