"""Prevent enum duplication

Revision ID: ad989f02bf68
Revises: ceaf10b758f4
Create Date: 2025-05-20 21:13:47.477099

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ad989f02bf68'
down_revision: Union[str, None] = 'ceaf10b758f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('referral_system', sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'REJECTED', 'CLOSED', name='referralstatus'), nullable=True))
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('ADMIN', 'PRIMARY_HOLDER', 'FAMILY_MEMBER', 'PRACTITIONER', 'CAREGIVER', 'PROFESSIONAL', name='userroleenum'),
               type_=sa.Enum('ADMIN', 'PRIMARY_HOLDER', 'FAMILY_MEMBER', 'PRACTITIONER', 'CAREGIVER', 'PROFESSIONAL', name='UserRoleInput'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=sa.Enum('ADMIN', 'PRIMARY_HOLDER', 'FAMILY_MEMBER', 'PRACTITIONER', 'CAREGIVER', 'PROFESSIONAL', name='UserRoleInput'),
               type_=postgresql.ENUM('ADMIN', 'PRIMARY_HOLDER', 'FAMILY_MEMBER', 'PRACTITIONER', 'CAREGIVER', 'PROFESSIONAL', name='userroleenum'),
               existing_nullable=False)
    op.drop_column('referral_system', 'status')
    # ### end Alembic commands ###
