"""initial

Revision ID: c7e50711d83a
Revises: 
Create Date: 2025-05-14 17:04:11.615970

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7e50711d83a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content_translations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content_key', sa.String(), nullable=False),
    sa.Column('language_code', sa.String(), nullable=False),
    sa.Column('content_type', sa.String(), nullable=False),
    sa.Column('translated_text', sa.String(), nullable=False),
    sa.Column('context', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_translations_id'), 'content_translations', ['id'], unique=False)
    op.create_table('cultural_health_resources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('contact', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('community', sa.Enum('FIRST_NATIONS', 'INUIT', 'METIS', 'ABORIGINAL', 'TORRES_STRAIT', 'OTHER', name='indigenouscommunity'), nullable=False),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('services_offered', sa.JSON(), nullable=True),
    sa.Column('cultural_specificity', sa.Text(), nullable=True),
    sa.Column('accessibility_notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cultural_health_resources_id'), 'cultural_health_resources', ['id'], unique=False)
    op.create_table('emergency_alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alert_id', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('NATURAL_DISASTER', 'PUBLIC_HEALTH', 'CIVIL_EMERGENCY', 'SECURITY_THREAT', 'INFRASTRUCTURE', 'ENVIRONMENTAL', 'OTHER', name='emergencyalerttype'), nullable=False),
    sa.Column('severity', sa.Enum('LOW', 'MODERATE', 'HIGH', 'CRITICAL', name='emergencyseverity'), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('affected_regions', sa.JSON(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('official_guidance', sa.JSON(), nullable=True),
    sa.Column('resources', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('additional_info', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('alert_id')
    )
    op.create_index(op.f('ix_emergency_alerts_id'), 'emergency_alerts', ['id'], unique=False)
    op.create_table('emergency_protocols',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('emergency_type', sa.Enum('MEDICAL', 'MENTAL_HEALTH', 'DOMESTIC_VIOLENCE', 'NATURAL_DISASTER', 'PUBLIC_SAFETY', 'OTHER', name='emergencytype'), nullable=False),
    sa.Column('severity', sa.Enum('LOW', 'MODERATE', 'HIGH', 'CRITICAL', name='emergencyseverity'), nullable=False),
    sa.Column('steps', sa.JSON(), nullable=False),
    sa.Column('required_resources', sa.JSON(), nullable=True),
    sa.Column('estimated_duration', sa.Integer(), nullable=True),
    sa.Column('success_criteria', sa.JSON(), nullable=True),
    sa.Column('last_reviewed', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emergency_protocols_id'), 'emergency_protocols', ['id'], unique=False)
    op.create_table('emergency_regions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('affected_areas', sa.JSON(), nullable=True),
    sa.Column('population_impact', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emergency_regions_id'), 'emergency_regions', ['id'], unique=False)
    op.create_table('emergency_resources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('contact', sa.String(), nullable=False),
    sa.Column('location_lat', sa.Float(), nullable=True),
    sa.Column('location_lon', sa.Float(), nullable=True),
    sa.Column('availability', sa.Boolean(), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('current_usage', sa.Integer(), nullable=True),
    sa.Column('response_time', sa.Integer(), nullable=True),
    sa.Column('coverage_area', sa.JSON(), nullable=True),
    sa.Column('specializations', sa.JSON(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emergency_resources_id'), 'emergency_resources', ['id'], unique=False)
    op.create_table('mental_health_resources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('content_type', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('target_audience', sa.JSON(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('difficulty_level', sa.String(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('author', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('related_conditions', sa.JSON(), nullable=True),
    sa.Column('estimated_time', sa.Integer(), nullable=True),
    sa.Column('prerequisites', sa.JSON(), nullable=True),
    sa.Column('learning_objectives', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mental_health_resources_id'), 'mental_health_resources', ['id'], unique=False)
    op.create_table('national_emergency_resources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('contact', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_national_emergency_resources_id'), 'national_emergency_resources', ['id'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    op.create_table('subscription_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('price_usd', sa.Float(), nullable=False),
    sa.Column('stripe_price_id_usd', sa.String(), nullable=True),
    sa.Column('features', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('billing_cycle', sa.Enum('MONTHLY', 'YEARLY', 'QUARTERLY', name='billingcycle'), nullable=True),
    sa.Column('trial_period_days', sa.Integer(), nullable=True),
    sa.Column('max_users', sa.Integer(), nullable=True),
    sa.Column('upgrade_path', sa.JSON(), nullable=True),
    sa.Column('downgrade_path', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_subscription_plans_id'), 'subscription_plans', ['id'], unique=False)
    op.create_table('support_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('condition_tag', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_private', sa.Boolean(), nullable=True),
    sa.Column('requires_approval', sa.Boolean(), nullable=True),
    sa.Column('moderator_ids', sa.String(), nullable=True),
    sa.Column('rules', sa.Text(), nullable=True),
    sa.Column('member_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('traditional_medicines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('community', sa.Enum('FIRST_NATIONS', 'INUIT', 'METIS', 'ABORIGINAL', 'TORRES_STRAIT', 'OTHER', name='indigenouscommunity'), nullable=False),
    sa.Column('uses', sa.JSON(), nullable=True),
    sa.Column('preparation_method', sa.Text(), nullable=True),
    sa.Column('dosage_guidelines', sa.Text(), nullable=True),
    sa.Column('contraindications', sa.JSON(), nullable=True),
    sa.Column('cultural_context', sa.Text(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_traditional_medicines_id'), 'traditional_medicines', ['id'], unique=False)
    op.create_table('emergency_response_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.String(), nullable=False),
    sa.Column('alert_id', sa.Integer(), nullable=False),
    sa.Column('alert_type', sa.Enum('NATURAL_DISASTER', 'PUBLIC_HEALTH', 'CIVIL_EMERGENCY', 'SECURITY_THREAT', 'INFRASTRUCTURE', 'ENVIRONMENTAL', 'OTHER', name='emergencyalerttype'), nullable=False),
    sa.Column('severity_levels', sa.JSON(), nullable=True),
    sa.Column('immediate_actions', sa.JSON(), nullable=True),
    sa.Column('resource_requirements', sa.JSON(), nullable=True),
    sa.Column('communication_protocols', sa.JSON(), nullable=True),
    sa.Column('evacuation_procedures', sa.JSON(), nullable=True),
    sa.Column('medical_response', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['alert_id'], ['emergency_alerts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plan_id')
    )
    op.create_index(op.f('ix_emergency_response_plans_id'), 'emergency_response_plans', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('role', sa.Enum('ADMIN', 'PRIMARY_HOLDER', 'FAMILY_MEMBER', 'PRACTITIONER', 'CAREGIVER', 'PROFESSIONAL', name='UserRoleInput'), nullable=False),
    sa.Column('subscription_id', sa.Integer(), nullable=True),
    sa.Column('stripe_customer_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscription_plans.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stripe_customer_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('accessibility_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('feature_used', sa.String(), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('access_log_metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accessibility_logs_id'), 'accessibility_logs', ['id'], unique=False)
    op.create_table('appointments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('doctor_name', sa.String(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('location', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_appointments_id'), 'appointments', ['id'], unique=False)
    op.create_table('care_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('practitioner_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('medications', sa.JSON(), nullable=True),
    sa.Column('exercises', sa.JSON(), nullable=True),
    sa.Column('diet_plan', sa.JSON(), nullable=True),
    sa.Column('lifestyle_changes', sa.JSON(), nullable=True),
    sa.Column('goals', sa.JSON(), nullable=True),
    sa.Column('checkpoints', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['practitioner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_care_plans_id'), 'care_plans', ['id'], unique=False)
    op.create_table('caregiver_assignments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('caregiver_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('tasks', sa.JSON(), nullable=True),
    sa.Column('schedule', sa.String(), nullable=True),
    sa.Column('emergency_contact', sa.String(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(), nullable=True),
    sa.Column('appointment_history', sa.JSON(), nullable=True),
    sa.Column('medication_tracking', sa.JSON(), nullable=True),
    sa.Column('monitoring_data', sa.JSON(), nullable=True),
    sa.Column('financial_support', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['caregiver_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_caregiver_assignments_id'), 'caregiver_assignments', ['id'], unique=False)
    op.create_table('caregivers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_caregivers_id'), 'caregivers', ['id'], unique=False)
    op.create_table('chronic_monitoring',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('condition', sa.String(), nullable=False),
    sa.Column('blood_pressure', sa.JSON(), nullable=True),
    sa.Column('blood_sugar', sa.JSON(), nullable=True),
    sa.Column('heart_rate', sa.JSON(), nullable=True),
    sa.Column('weight', sa.JSON(), nullable=True),
    sa.Column('medications', sa.JSON(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chronic_monitoring_id'), 'chronic_monitoring', ['id'], unique=False)
    op.create_table('community_posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_anonymous', sa.Boolean(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'FLAGGED', 'DELETED', name='moderationstatus'), nullable=True),
    sa.Column('moderation_notes', sa.Text(), nullable=True),
    sa.Column('moderated_by', sa.Integer(), nullable=True),
    sa.Column('moderated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_edited_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('edit_history', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['support_groups.id'], ),
    sa.ForeignKeyConstraint(['moderated_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_community_posts_category'), 'community_posts', ['category'], unique=False)
    op.create_index(op.f('ix_community_posts_created_at'), 'community_posts', ['created_at'], unique=False)
    op.create_index(op.f('ix_community_posts_group_id'), 'community_posts', ['group_id'], unique=False)
    op.create_index(op.f('ix_community_posts_id'), 'community_posts', ['id'], unique=False)
    op.create_table('digital_credentials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('credential_type', sa.Enum('SMART_HEALTH_CARD', 'MEDICARE_CARD', 'VACCINATION_RECORD', 'MEDICAL_RECORD', 'PRESCRIPTION', 'LAB_RESULT', 'EMERGENCY_HEALTH_ID', name='credentialtype'), nullable=False),
    sa.Column('credential_data', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'EXPIRED', 'REVOKED', 'PENDING', name='credentialstatus'), nullable=False),
    sa.Column('issued_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('issuer', sa.String(), nullable=False),
    sa.Column('verification_status', sa.Boolean(), nullable=True),
    sa.Column('verification_timestamp', sa.DateTime(), nullable=True),
    sa.Column('credential_metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_digital_credentials_id'), 'digital_credentials', ['id'], unique=False)
    op.create_table('ehr_connections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ehr_system', sa.Enum('EPIC', 'CERNER', 'MY_HEALTH_RECORD', 'NATIONAL_IMMUNIZATION', 'NATIONAL_PRESCRIPTION', 'NATIONAL_HEALTH_ID', 'CUSTOM', name='ehrsystem'), nullable=False),
    sa.Column('connection_config', sa.JSON(), nullable=False),
    sa.Column('access_token', sa.String(), nullable=False),
    sa.Column('refresh_token', sa.String(), nullable=True),
    sa.Column('token_expires_at', sa.DateTime(), nullable=True),
    sa.Column('last_sync', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ehr_connections_id'), 'ehr_connections', ['id'], unique=False)
    op.create_table('emergency_alert_subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('alert_id', sa.Integer(), nullable=False),
    sa.Column('alert_types', sa.JSON(), nullable=True),
    sa.Column('regions', sa.JSON(), nullable=True),
    sa.Column('severity_threshold', sa.Enum('LOW', 'MODERATE', 'HIGH', 'CRITICAL', name='emergencyseverity'), nullable=False),
    sa.Column('notification_preferences', sa.JSON(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['alert_id'], ['emergency_alerts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emergency_alert_subscriptions_id'), 'emergency_alert_subscriptions', ['id'], unique=False)
    op.create_table('emergency_health_ids',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('blood_type', sa.Enum('A_POSITIVE', 'A_NEGATIVE', 'B_POSITIVE', 'B_NEGATIVE', 'AB_POSITIVE', 'AB_NEGATIVE', 'O_POSITIVE', 'O_NEGATIVE', name='bloodtype'), nullable=True),
    sa.Column('allergies', sa.Text(), nullable=True),
    sa.Column('medications', sa.Text(), nullable=True),
    sa.Column('critical_conditions', sa.Text(), nullable=True),
    sa.Column('organ_donor_status', sa.Boolean(), nullable=True),
    sa.Column('emergency_contact_name', sa.String(), nullable=True),
    sa.Column('emergency_contact_phone', sa.String(), nullable=True),
    sa.Column('primary_care_physician', sa.String(), nullable=True),
    sa.Column('physician_contact', sa.String(), nullable=True),
    sa.Column('preferred_language', sa.String(), nullable=True),
    sa.Column('insurance_provider', sa.String(), nullable=True),
    sa.Column('insurance_number', sa.String(), nullable=True),
    sa.Column('additional_notes', sa.Text(), nullable=True),
    sa.Column('qr_code', sa.Text(), nullable=True),
    sa.Column('qr_code_enabled', sa.Boolean(), nullable=True),
    sa.Column('lock_screen_enabled', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_accessed', sa.DateTime(), nullable=True),
    sa.Column('access_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_emergency_health_ids_id'), 'emergency_health_ids', ['id'], unique=False)
    op.create_table('emergency_responses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('emergency_type', sa.Enum('MEDICAL', 'MENTAL_HEALTH', 'DOMESTIC_VIOLENCE', 'NATURAL_DISASTER', 'PUBLIC_SAFETY', 'OTHER', name='emergencytype'), nullable=False),
    sa.Column('severity', sa.Enum('LOW', 'MODERATE', 'HIGH', 'CRITICAL', name='emergencyseverity'), nullable=False),
    sa.Column('location_lat', sa.Float(), nullable=True),
    sa.Column('location_lon', sa.Float(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('reported_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('assigned_to', sa.Integer(), nullable=True),
    sa.Column('actions_taken', sa.JSON(), nullable=False),
    sa.Column('resources_used', sa.JSON(), nullable=True),
    sa.Column('follow_up_required', sa.Boolean(), nullable=True),
    sa.Column('follow_up_notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emergency_responses_id'), 'emergency_responses', ['id'], unique=False)
    op.create_table('emergency_training',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('training_type', sa.String(), nullable=False),
    sa.Column('certification_id', sa.String(), nullable=True),
    sa.Column('issue_date', sa.DateTime(), nullable=False),
    sa.Column('expiry_date', sa.DateTime(), nullable=True),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('verification_document', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emergency_training_id'), 'emergency_training', ['id'], unique=False)
    op.create_table('family_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('family_member_id', sa.Integer(), nullable=False),
    sa.Column('relationship_type', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('sharing_preferences', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['family_member_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_family_links_id'), 'family_links', ['id'], unique=False)
    op.create_table('gamification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.Column('badges', sa.String(), nullable=True),
    sa.Column('completed_challenges', sa.Integer(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gamification_id'), 'gamification', ['id'], unique=False)
    op.create_table('group_memberships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['support_groups.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('health_checkin_schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('frequency', sa.String(), nullable=False),
    sa.Column('preferred_time', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_check_in', sa.DateTime(), nullable=True),
    sa.Column('next_check_in', sa.DateTime(), nullable=True),
    sa.Column('reminder_preferences', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_health_checkin_schedules_id'), 'health_checkin_schedules', ['id'], unique=False)
    op.create_table('health_checkins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('check_in_time', sa.DateTime(), nullable=True),
    sa.Column('health_metrics', sa.JSON(), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('requires_attention', sa.Boolean(), nullable=True),
    sa.Column('attention_reason', sa.String(), nullable=True),
    sa.Column('notification_sent', sa.Boolean(), nullable=True),
    sa.Column('notification_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_health_checkins_id'), 'health_checkins', ['id'], unique=False)
    op.create_table('health_diary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('symptoms', sa.JSON(), nullable=True),
    sa.Column('mood', sa.Integer(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_health_diary_id'), 'health_diary', ['id'], unique=False)
    op.create_table('health_insights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('insight_type', sa.Enum('SYMPTOM_ANALYSIS', 'TREND_PREDICTION', 'RISK_ASSESSMENT', 'LIFESTYLE_INSIGHT', 'MEDICATION_INSIGHT', 'MENTAL_HEALTH', 'CHRONIC_CONDITION', name='insighttype'), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.Column('insight_data', sa.JSON(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('is_actionable', sa.Boolean(), nullable=True),
    sa.Column('action_taken', sa.Boolean(), nullable=True),
    sa.Column('action_taken_at', sa.DateTime(), nullable=True),
    sa.Column('feedback_score', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_health_insights_id'), 'health_insights', ['id'], unique=False)
    op.create_table('health_predictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('prediction_type', sa.String(), nullable=False),
    sa.Column('predicted_at', sa.DateTime(), nullable=False),
    sa.Column('prediction_window', sa.Integer(), nullable=False),
    sa.Column('prediction_data', sa.JSON(), nullable=False),
    sa.Column('confidence', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='predictionconfidence'), nullable=False),
    sa.Column('accuracy_score', sa.Float(), nullable=True),
    sa.Column('occurred', sa.Boolean(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_health_predictions_id'), 'health_predictions', ['id'], unique=False)
    op.create_table('health_risk_factors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('risk_type', sa.String(), nullable=False),
    sa.Column('risk_level', sa.String(), nullable=False),
    sa.Column('identified_at', sa.DateTime(), nullable=False),
    sa.Column('contributing_factors', sa.JSON(), nullable=False),
    sa.Column('mitigation_strategies', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_assessed', sa.DateTime(), nullable=False),
    sa.Column('assessment_frequency', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_health_risk_factors_id'), 'health_risk_factors', ['id'], unique=False)
    op.create_table('health_tips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tip', sa.String(), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_health_tips_id'), 'health_tips', ['id'], unique=False)
    op.create_table('health_trends',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('trend_type', sa.String(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('trend_data', sa.JSON(), nullable=False),
    sa.Column('significance_score', sa.Float(), nullable=False),
    sa.Column('impact_level', sa.String(), nullable=False),
    sa.Column('recommendations', sa.JSON(), nullable=True),
    sa.Column('is_monitored', sa.Boolean(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_health_trends_id'), 'health_trends', ['id'], unique=False)
    op.create_table('indigenous_health_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('community', sa.Enum('FIRST_NATIONS', 'INUIT', 'METIS', 'ABORIGINAL', 'TORRES_STRAIT', 'OTHER', name='indigenouscommunity'), nullable=False),
    sa.Column('cultural_practices', sa.JSON(), nullable=True),
    sa.Column('traditional_medicines', sa.JSON(), nullable=True),
    sa.Column('health_resources', sa.JSON(), nullable=True),
    sa.Column('cultural_preferences', sa.JSON(), nullable=True),
    sa.Column('traditional_healing_consent', sa.Boolean(), nullable=True),
    sa.Column('cultural_support_network', sa.JSON(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_indigenous_health_profiles_id'), 'indigenous_health_profiles', ['id'], unique=False)
    op.create_table('insurance_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('provider_name', sa.String(), nullable=False),
    sa.Column('policy_number', sa.String(), nullable=False),
    sa.Column('coverage_start', sa.Date(), nullable=False),
    sa.Column('coverage_end', sa.Date(), nullable=False),
    sa.Column('deductible', sa.Integer(), nullable=True),
    sa.Column('premium_amount', sa.Integer(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('verification_status', sa.Enum('PENDING', 'VERIFIED', 'REJECTED', name='verificationstatusenum'), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('policy_number')
    )
    op.create_index(op.f('ix_insurance_plans_id'), 'insurance_plans', ['id'], unique=False)
    op.create_table('leaderboard',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('total_points', sa.Integer(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leaderboard_id'), 'leaderboard', ['id'], unique=False)
    op.create_table('medications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('dosage', sa.String(), nullable=False),
    sa.Column('frequency', sa.String(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medications_id'), 'medications', ['id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('receiver_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('message_type', sa.String(), nullable=False),
    sa.Column('retention_period', sa.Integer(), nullable=False),
    sa.Column('audit_log', sa.JSON(), nullable=True),
    sa.Column('is_encrypted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('message_metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['receiver_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_id'), 'messages', ['id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_table('operational_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('metric_name', sa.String(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('target_value', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('time_period', sa.String(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_operational_metrics_id'), 'operational_metrics', ['id'], unique=False)
    op.create_table('pharmacy_orders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('medications', sa.JSON(), nullable=False),
    sa.Column('delivery_address', sa.String(), nullable=False),
    sa.Column('payment_method', sa.String(), nullable=True),
    sa.Column('insurance_used', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('estimated_delivery', sa.DateTime(), nullable=True),
    sa.Column('order_date', sa.DateTime(), nullable=True),
    sa.Column('stripe_payment_intent_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pharmacy_orders_id'), 'pharmacy_orders', ['id'], unique=False)
    op.create_table('population_health_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('metric_name', sa.String(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('target_value', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('demographic_breakdown', sa.JSON(), nullable=True),
    sa.Column('time_period', sa.String(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_population_health_metrics_id'), 'population_health_metrics', ['id'], unique=False)
    op.create_table('practitioners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('specialty', sa.String(), nullable=False),
    sa.Column('contact_info', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_practitioners_id'), 'practitioners', ['id'], unique=False)
    op.create_table('professionals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('specialty', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('accepts_insurance', sa.Boolean(), nullable=True),
    sa.Column('online_available', sa.Boolean(), nullable=True),
    sa.Column('contact_info', sa.String(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('credentials', sa.JSON(), nullable=True),
    sa.Column('languages', sa.JSON(), nullable=True),
    sa.Column('specialties', sa.JSON(), nullable=True),
    sa.Column('availability', sa.JSON(), nullable=True),
    sa.Column('emergency_available', sa.Boolean(), nullable=True),
    sa.Column('therapy_types', sa.JSON(), nullable=True),
    sa.Column('approaches', sa.JSON(), nullable=True),
    sa.Column('session_duration', sa.Integer(), nullable=False),
    sa.Column('session_fee', sa.Float(), nullable=True),
    sa.Column('sliding_scale', sa.Boolean(), nullable=True),
    sa.Column('min_fee', sa.Float(), nullable=True),
    sa.Column('max_fee', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_professionals_id'), 'professionals', ['id'], unique=False)
    op.create_table('provider_analytics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('report_type', sa.Enum('POPULATION_HEALTH', 'PATIENT_OUTCOMES', 'OPERATIONAL', 'FINANCIAL', 'QUALITY_METRICS', name='reporttype'), nullable=False),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.Column('time_period', sa.String(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_provider_analytics_id'), 'provider_analytics', ['id'], unique=False)
    op.create_table('quality_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('metric_name', sa.String(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('benchmark', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('time_period', sa.String(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quality_metrics_id'), 'quality_metrics', ['id'], unique=False)
    op.create_table('referrals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('from_practitioner_id', sa.Integer(), nullable=False),
    sa.Column('to_practitioner_id', sa.Integer(), nullable=False),
    sa.Column('specialist_type', sa.Enum('CARDIOLOGIST', 'NEUROLOGIST', 'DERMATOLOGIST', 'ORTHOPEDIST', 'PEDIATRICIAN', 'PSYCHIATRIST', name='specialisttype'), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('priority', sa.Enum('ROUTINE', 'URGENT', 'EMERGENCY', name='referralpriority'), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'REJECTED', 'CLOSED', 'IN_PROGRESS', 'COMPLETED', name='referralstatus'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('appointment_date', sa.DateTime(), nullable=True),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('medical_history_required', sa.Boolean(), nullable=True),
    sa.Column('test_results_required', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['from_practitioner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['to_practitioner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_referrals_id'), 'referrals', ['id'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('report_data', sa.String(), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_id'), 'reports', ['id'], unique=False)
    op.create_table('subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('stripe_subscription_id', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'PAST_DUE', 'CANCELED', 'INCOMPLETE', 'INCOMPLETE_EXPIRED', 'TRIALING', 'UNPAID', name='subscriptionstatus'), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('trial_end', sa.DateTime(), nullable=True),
    sa.Column('cancel_at_period_end', sa.Boolean(), nullable=True),
    sa.Column('current_period_start', sa.DateTime(), nullable=True),
    sa.Column('current_period_end', sa.DateTime(), nullable=True),
    sa.Column('billing_cycle_anchor', sa.DateTime(), nullable=True),
    sa.Column('last_payment_status', sa.String(), nullable=True),
    sa.Column('last_payment_date', sa.DateTime(), nullable=True),
    sa.Column('next_payment_date', sa.DateTime(), nullable=True),
    sa.Column('payment_method_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['subscription_plans.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stripe_subscription_id')
    )
    op.create_index(op.f('ix_subscriptions_id'), 'subscriptions', ['id'], unique=False)
    op.create_table('symptom_analysis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('symptoms', sa.String(), nullable=False),
    sa.Column('analysis_result', sa.String(), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_symptom_analysis_id'), 'symptom_analysis', ['id'], unique=False)
    op.create_table('user_accessibility',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('preferred_language', sa.String(), nullable=False),
    sa.Column('secondary_languages', sa.JSON(), nullable=True),
    sa.Column('screen_reader_enabled', sa.Boolean(), nullable=True),
    sa.Column('high_contrast_mode', sa.Boolean(), nullable=True),
    sa.Column('font_size', sa.String(), nullable=True),
    sa.Column('reduced_motion', sa.Boolean(), nullable=True),
    sa.Column('voice_input_enabled', sa.Boolean(), nullable=True),
    sa.Column('voice_output_enabled', sa.Boolean(), nullable=True),
    sa.Column('preferred_voice', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_user_accessibility_id'), 'user_accessibility', ['id'], unique=False)
    op.create_table('user_oauth_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('access_token', sa.String(), nullable=False),
    sa.Column('refresh_token', sa.String(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_oauth_tokens_id'), 'user_oauth_tokens', ['id'], unique=False)
    op.create_table('user_roles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.create_table('vaccination_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('vaccine_name', sa.String(), nullable=False),
    sa.Column('dose_number', sa.Integer(), nullable=False),
    sa.Column('date_administered', sa.Date(), nullable=False),
    sa.Column('healthcare_provider', sa.String(), nullable=False),
    sa.Column('next_due_date', sa.Date(), nullable=True),
    sa.Column('user_email', sa.String(), nullable=True),
    sa.Column('user_phone', sa.String(), nullable=True),
    sa.Column('reminder_sent', sa.Boolean(), nullable=True),
    sa.Column('synced_with_national', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vaccination_records_id'), 'vaccination_records', ['id'], unique=False)
    op.create_table('care_plan_daily_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('care_plan_id', sa.Integer(), nullable=False),
    sa.Column('task_type', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('scheduled_time', sa.String(), nullable=True),
    sa.Column('frequency', sa.String(), nullable=False),
    sa.Column('days_of_week', sa.JSON(), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('reminder_enabled', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['care_plan_id'], ['care_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_care_plan_daily_tasks_id'), 'care_plan_daily_tasks', ['id'], unique=False)
    op.create_table('care_plan_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('care_plan_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('completed_tasks', sa.JSON(), nullable=True),
    sa.Column('challenges', sa.JSON(), nullable=True),
    sa.Column('next_steps', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['care_plan_id'], ['care_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_care_plan_progress_id'), 'care_plan_progress', ['id'], unique=False)
    op.create_table('community_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'FLAGGED', 'DELETED', name='moderationstatus'), nullable=True),
    sa.Column('moderation_notes', sa.Text(), nullable=True),
    sa.Column('moderated_by', sa.Integer(), nullable=True),
    sa.Column('moderated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('parent_comment_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['moderated_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['parent_comment_id'], ['community_comments.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['community_posts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_community_comments_id'), 'community_comments', ['id'], unique=False)
    op.create_table('community_likes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['community_posts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_community_likes_id'), 'community_likes', ['id'], unique=False)
    op.create_table('community_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='reportseverity'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['community_posts.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_community_reports_id'), 'community_reports', ['id'], unique=False)
    op.create_table('credential_shares',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('credential_id', sa.Integer(), nullable=False),
    sa.Column('recipient_email', sa.String(), nullable=False),
    sa.Column('recipient_name', sa.String(), nullable=False),
    sa.Column('access_duration', sa.Integer(), nullable=True),
    sa.Column('purpose', sa.String(), nullable=False),
    sa.Column('scope', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['credential_id'], ['digital_credentials.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_credential_shares_id'), 'credential_shares', ['id'], unique=False)
    op.create_table('credential_verifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('credential_id', sa.Integer(), nullable=False),
    sa.Column('verification_method', sa.String(), nullable=False),
    sa.Column('verification_data', sa.JSON(), nullable=False),
    sa.Column('verification_result', sa.Boolean(), nullable=False),
    sa.Column('verification_timestamp', sa.DateTime(), nullable=False),
    sa.Column('verification_metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['credential_id'], ['digital_credentials.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_credential_verifications_id'), 'credential_verifications', ['id'], unique=False)
    op.create_table('crisis_interventions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date_time', sa.DateTime(), nullable=False),
    sa.Column('crisis_type', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('intervention_type', sa.String(), nullable=False),
    sa.Column('responder_id', sa.Integer(), nullable=True),
    sa.Column('actions_taken', sa.JSON(), nullable=False),
    sa.Column('outcome', sa.String(), nullable=False),
    sa.Column('follow_up_required', sa.Boolean(), nullable=True),
    sa.Column('follow_up_date', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('emergency_services_contacted', sa.Boolean(), nullable=True),
    sa.Column('safety_plan_created', sa.Boolean(), nullable=True),
    sa.Column('support_network_contacted', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['responder_id'], ['professionals.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crisis_interventions_id'), 'crisis_interventions', ['id'], unique=False)
    op.create_table('ehr_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('connection_id', sa.Integer(), nullable=False),
    sa.Column('medical_history', sa.JSON(), nullable=True),
    sa.Column('medications', sa.JSON(), nullable=True),
    sa.Column('procedures', sa.JSON(), nullable=True),
    sa.Column('allergies', sa.JSON(), nullable=True),
    sa.Column('immunizations', sa.JSON(), nullable=True),
    sa.Column('last_synced', sa.DateTime(), nullable=True),
    sa.Column('sync_status', sa.String(), nullable=True),
    sa.Column('sync_message', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['connection_id'], ['ehr_connections.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ehr_records_id'), 'ehr_records', ['id'], unique=False)
    op.create_table('family_health_summaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('family_id', sa.Integer(), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('overall_health_status', sa.String(), nullable=True),
    sa.Column('active_conditions', sa.JSON(), nullable=True),
    sa.Column('medications', sa.JSON(), nullable=True),
    sa.Column('allergies', sa.JSON(), nullable=True),
    sa.Column('upcoming_appointments', sa.JSON(), nullable=True),
    sa.Column('recent_health_events', sa.JSON(), nullable=True),
    sa.Column('risk_factors', sa.JSON(), nullable=True),
    sa.Column('preventive_care', sa.JSON(), nullable=True),
    sa.Column('lifestyle_factors', sa.JSON(), nullable=True),
    sa.Column('emergency_contacts', sa.JSON(), nullable=True),
    sa.Column('care_coordination', sa.JSON(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['family_id'], ['family_links.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_family_health_summaries_id'), 'family_health_summaries', ['id'], unique=False)
    op.create_table('indigenous_health_support_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('support_type', sa.String(), nullable=False),
    sa.Column('cultural_context', sa.Text(), nullable=True),
    sa.Column('specific_needs', sa.JSON(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('emergency', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('response', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['indigenous_health_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_indigenous_health_support_requests_id'), 'indigenous_health_support_requests', ['id'], unique=False)
    op.create_table('insurance_coverage_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('insurance_plan_id', sa.Integer(), nullable=False),
    sa.Column('coverage_type', sa.String(), nullable=False),
    sa.Column('benefits', sa.String(), nullable=True),
    sa.Column('exclusions', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['insurance_plan_id'], ['insurance_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_insurance_coverage_details_id'), 'insurance_coverage_details', ['id'], unique=False)
    op.create_table('medicare_claims',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('insurance_plan_id', sa.Integer(), nullable=False),
    sa.Column('claim_id', sa.String(), nullable=False),
    sa.Column('claim_date', sa.Date(), nullable=False),
    sa.Column('claim_amount', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['insurance_plan_id'], ['insurance_plans.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('claim_id')
    )
    op.create_index(op.f('ix_medicare_claims_id'), 'medicare_claims', ['id'], unique=False)
    op.create_table('medication_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('medication_id', sa.Integer(), nullable=False),
    sa.Column('taken_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['medication_id'], ['medications.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medication_logs_id'), 'medication_logs', ['id'], unique=False)
    op.create_table('mental_health_assessments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('assessment_type', sa.String(), nullable=False),
    sa.Column('scores', sa.JSON(), nullable=False),
    sa.Column('total_score', sa.Integer(), nullable=False),
    sa.Column('risk_level', sa.String(), nullable=False),
    sa.Column('recommendations', sa.JSON(), nullable=True),
    sa.Column('follow_up_date', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('therapist_id', sa.Integer(), nullable=True),
    sa.Column('assessment_tools', sa.JSON(), nullable=True),
    sa.Column('symptoms', sa.JSON(), nullable=True),
    sa.Column('triggers', sa.JSON(), nullable=True),
    sa.Column('coping_strategies', sa.JSON(), nullable=True),
    sa.Column('support_system', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['therapist_id'], ['professionals.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mental_health_assessments_id'), 'mental_health_assessments', ['id'], unique=False)
    op.create_table('message_audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('additional_info', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_audit_logs_id'), 'message_audit_logs', ['id'], unique=False)
    op.create_table('national_database_connections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ehr_connection_id', sa.Integer(), nullable=False),
    sa.Column('database_type', sa.Enum('MY_HEALTH_RECORD', 'IMMUNIZATION_REGISTRY', 'PRESCRIPTION_DATABASE', 'HEALTH_IDENTIFIER', 'MEDICARE', 'MEDICAID', name='nationaldatabasetype'), nullable=False),
    sa.Column('connection_config', sa.JSON(), nullable=False),
    sa.Column('access_token', sa.String(), nullable=True),
    sa.Column('refresh_token', sa.String(), nullable=True),
    sa.Column('token_expires_at', sa.DateTime(), nullable=True),
    sa.Column('last_sync', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ehr_connection_id'], ['ehr_connections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_national_database_connections_id'), 'national_database_connections', ['id'], unique=False)
    op.create_table('out_of_pocket_costs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('insurance_plan_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['insurance_plan_id'], ['insurance_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_out_of_pocket_costs_id'), 'out_of_pocket_costs', ['id'], unique=False)
    op.create_table('practitioner_patient',
    sa.Column('practitioner_id', sa.Integer(), nullable=True),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['practitioner_id'], ['practitioners.id'], )
    )
    op.create_table('referral_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('referral_id', sa.Integer(), nullable=False),
    sa.Column('document_url', sa.String(), nullable=False),
    sa.Column('uploaded_by', sa.Integer(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.Column('document_type', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['referral_id'], ['referrals.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_referral_documents_id'), 'referral_documents', ['id'], unique=False)
    op.create_table('referral_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('referral_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('performed_by', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['performed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['referral_id'], ['referrals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_referral_history_id'), 'referral_history', ['id'], unique=False)
    op.create_table('telehealth_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('practitioner_id', sa.Integer(), nullable=False),
    sa.Column('session_status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['practitioner_id'], ['practitioners.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_telehealth_sessions_id'), 'telehealth_sessions', ['id'], unique=False)
    op.create_table('therapist_appointments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('therapist_id', sa.Integer(), nullable=False),
    sa.Column('date_time', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('payment_status', sa.String(), nullable=False),
    sa.Column('video_call_link', sa.String(), nullable=True),
    sa.Column('session_type', sa.Enum('INDIVIDUAL', 'GROUP', 'COUPLES', 'FAMILY', 'CRISIS', name='therapytype'), nullable=False),
    sa.Column('approach', sa.Enum('CBT', 'DBT', 'PSYCHODYNAMIC', 'HUMANISTIC', 'MINDFULNESS', 'OTHER', name='therapyapproach'), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('follow_up_required', sa.Boolean(), nullable=True),
    sa.Column('follow_up_date', sa.DateTime(), nullable=True),
    sa.Column('session_summary', sa.Text(), nullable=True),
    sa.Column('goals_discussed', sa.JSON(), nullable=True),
    sa.Column('homework_assigned', sa.JSON(), nullable=True),
    sa.Column('next_session_agenda', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['therapist_id'], ['professionals.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_therapist_appointments_id'), 'therapist_appointments', ['id'], unique=False)
    op.create_table('therapist_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('therapist_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('review_text', sa.Text(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('helpful_votes', sa.Integer(), nullable=True),
    sa.Column('verified_session', sa.Boolean(), nullable=True),
    sa.Column('session_date', sa.DateTime(), nullable=True),
    sa.Column('therapy_type', sa.Enum('INDIVIDUAL', 'GROUP', 'COUPLES', 'FAMILY', 'CRISIS', name='therapytype'), nullable=True),
    sa.Column('approach', sa.Enum('CBT', 'DBT', 'PSYCHODYNAMIC', 'HUMANISTIC', 'MINDFULNESS', 'OTHER', name='therapyapproach'), nullable=True),
    sa.ForeignKeyConstraint(['therapist_id'], ['professionals.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_therapist_reviews_id'), 'therapist_reviews', ['id'], unique=False)
    op.create_table('fhir_resource_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('resource_type', sa.String(), nullable=False),
    sa.Column('resource_id', sa.String(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('source_system', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['record_id'], ['ehr_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fhir_resource_cache_id'), 'fhir_resource_cache', ['id'], unique=False)
    op.create_table('national_database_sync_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('connection_id', sa.Integer(), nullable=False),
    sa.Column('sync_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('data_synced', sa.JSON(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['connection_id'], ['national_database_connections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_national_database_sync_records_id'), 'national_database_sync_records', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_national_database_sync_records_id'), table_name='national_database_sync_records')
    op.drop_table('national_database_sync_records')
    op.drop_index(op.f('ix_fhir_resource_cache_id'), table_name='fhir_resource_cache')
    op.drop_table('fhir_resource_cache')
    op.drop_index(op.f('ix_therapist_reviews_id'), table_name='therapist_reviews')
    op.drop_table('therapist_reviews')
    op.drop_index(op.f('ix_therapist_appointments_id'), table_name='therapist_appointments')
    op.drop_table('therapist_appointments')
    op.drop_index(op.f('ix_telehealth_sessions_id'), table_name='telehealth_sessions')
    op.drop_table('telehealth_sessions')
    op.drop_index(op.f('ix_referral_history_id'), table_name='referral_history')
    op.drop_table('referral_history')
    op.drop_index(op.f('ix_referral_documents_id'), table_name='referral_documents')
    op.drop_table('referral_documents')
    op.drop_table('practitioner_patient')
    op.drop_index(op.f('ix_out_of_pocket_costs_id'), table_name='out_of_pocket_costs')
    op.drop_table('out_of_pocket_costs')
    op.drop_index(op.f('ix_national_database_connections_id'), table_name='national_database_connections')
    op.drop_table('national_database_connections')
    op.drop_index(op.f('ix_message_audit_logs_id'), table_name='message_audit_logs')
    op.drop_table('message_audit_logs')
    op.drop_index(op.f('ix_mental_health_assessments_id'), table_name='mental_health_assessments')
    op.drop_table('mental_health_assessments')
    op.drop_index(op.f('ix_medication_logs_id'), table_name='medication_logs')
    op.drop_table('medication_logs')
    op.drop_index(op.f('ix_medicare_claims_id'), table_name='medicare_claims')
    op.drop_table('medicare_claims')
    op.drop_index(op.f('ix_insurance_coverage_details_id'), table_name='insurance_coverage_details')
    op.drop_table('insurance_coverage_details')
    op.drop_index(op.f('ix_indigenous_health_support_requests_id'), table_name='indigenous_health_support_requests')
    op.drop_table('indigenous_health_support_requests')
    op.drop_index(op.f('ix_family_health_summaries_id'), table_name='family_health_summaries')
    op.drop_table('family_health_summaries')
    op.drop_index(op.f('ix_ehr_records_id'), table_name='ehr_records')
    op.drop_table('ehr_records')
    op.drop_index(op.f('ix_crisis_interventions_id'), table_name='crisis_interventions')
    op.drop_table('crisis_interventions')
    op.drop_index(op.f('ix_credential_verifications_id'), table_name='credential_verifications')
    op.drop_table('credential_verifications')
    op.drop_index(op.f('ix_credential_shares_id'), table_name='credential_shares')
    op.drop_table('credential_shares')
    op.drop_index(op.f('ix_community_reports_id'), table_name='community_reports')
    op.drop_table('community_reports')
    op.drop_index(op.f('ix_community_likes_id'), table_name='community_likes')
    op.drop_table('community_likes')
    op.drop_index(op.f('ix_community_comments_id'), table_name='community_comments')
    op.drop_table('community_comments')
    op.drop_index(op.f('ix_care_plan_progress_id'), table_name='care_plan_progress')
    op.drop_table('care_plan_progress')
    op.drop_index(op.f('ix_care_plan_daily_tasks_id'), table_name='care_plan_daily_tasks')
    op.drop_table('care_plan_daily_tasks')
    op.drop_index(op.f('ix_vaccination_records_id'), table_name='vaccination_records')
    op.drop_table('vaccination_records')
    op.drop_table('user_roles')
    op.drop_index(op.f('ix_user_oauth_tokens_id'), table_name='user_oauth_tokens')
    op.drop_table('user_oauth_tokens')
    op.drop_index(op.f('ix_user_accessibility_id'), table_name='user_accessibility')
    op.drop_table('user_accessibility')
    op.drop_index(op.f('ix_symptom_analysis_id'), table_name='symptom_analysis')
    op.drop_table('symptom_analysis')
    op.drop_index(op.f('ix_subscriptions_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_reports_id'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_referrals_id'), table_name='referrals')
    op.drop_table('referrals')
    op.drop_index(op.f('ix_quality_metrics_id'), table_name='quality_metrics')
    op.drop_table('quality_metrics')
    op.drop_index(op.f('ix_provider_analytics_id'), table_name='provider_analytics')
    op.drop_table('provider_analytics')
    op.drop_index(op.f('ix_professionals_id'), table_name='professionals')
    op.drop_table('professionals')
    op.drop_index(op.f('ix_practitioners_id'), table_name='practitioners')
    op.drop_table('practitioners')
    op.drop_index(op.f('ix_population_health_metrics_id'), table_name='population_health_metrics')
    op.drop_table('population_health_metrics')
    op.drop_index(op.f('ix_pharmacy_orders_id'), table_name='pharmacy_orders')
    op.drop_table('pharmacy_orders')
    op.drop_index(op.f('ix_operational_metrics_id'), table_name='operational_metrics')
    op.drop_table('operational_metrics')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_messages_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_medications_id'), table_name='medications')
    op.drop_table('medications')
    op.drop_index(op.f('ix_leaderboard_id'), table_name='leaderboard')
    op.drop_table('leaderboard')
    op.drop_index(op.f('ix_insurance_plans_id'), table_name='insurance_plans')
    op.drop_table('insurance_plans')
    op.drop_index(op.f('ix_indigenous_health_profiles_id'), table_name='indigenous_health_profiles')
    op.drop_table('indigenous_health_profiles')
    op.drop_index(op.f('ix_health_trends_id'), table_name='health_trends')
    op.drop_table('health_trends')
    op.drop_index(op.f('ix_health_tips_id'), table_name='health_tips')
    op.drop_table('health_tips')
    op.drop_index(op.f('ix_health_risk_factors_id'), table_name='health_risk_factors')
    op.drop_table('health_risk_factors')
    op.drop_index(op.f('ix_health_predictions_id'), table_name='health_predictions')
    op.drop_table('health_predictions')
    op.drop_index(op.f('ix_health_insights_id'), table_name='health_insights')
    op.drop_table('health_insights')
    op.drop_index(op.f('ix_health_diary_id'), table_name='health_diary')
    op.drop_table('health_diary')
    op.drop_index(op.f('ix_health_checkins_id'), table_name='health_checkins')
    op.drop_table('health_checkins')
    op.drop_index(op.f('ix_health_checkin_schedules_id'), table_name='health_checkin_schedules')
    op.drop_table('health_checkin_schedules')
    op.drop_table('group_memberships')
    op.drop_index(op.f('ix_gamification_id'), table_name='gamification')
    op.drop_table('gamification')
    op.drop_index(op.f('ix_family_links_id'), table_name='family_links')
    op.drop_table('family_links')
    op.drop_index(op.f('ix_emergency_training_id'), table_name='emergency_training')
    op.drop_table('emergency_training')
    op.drop_index(op.f('ix_emergency_responses_id'), table_name='emergency_responses')
    op.drop_table('emergency_responses')
    op.drop_index(op.f('ix_emergency_health_ids_id'), table_name='emergency_health_ids')
    op.drop_table('emergency_health_ids')
    op.drop_index(op.f('ix_emergency_alert_subscriptions_id'), table_name='emergency_alert_subscriptions')
    op.drop_table('emergency_alert_subscriptions')
    op.drop_index(op.f('ix_ehr_connections_id'), table_name='ehr_connections')
    op.drop_table('ehr_connections')
    op.drop_index(op.f('ix_digital_credentials_id'), table_name='digital_credentials')
    op.drop_table('digital_credentials')
    op.drop_index(op.f('ix_community_posts_id'), table_name='community_posts')
    op.drop_index(op.f('ix_community_posts_group_id'), table_name='community_posts')
    op.drop_index(op.f('ix_community_posts_created_at'), table_name='community_posts')
    op.drop_index(op.f('ix_community_posts_category'), table_name='community_posts')
    op.drop_table('community_posts')
    op.drop_index(op.f('ix_chronic_monitoring_id'), table_name='chronic_monitoring')
    op.drop_table('chronic_monitoring')
    op.drop_index(op.f('ix_caregivers_id'), table_name='caregivers')
    op.drop_table('caregivers')
    op.drop_index(op.f('ix_caregiver_assignments_id'), table_name='caregiver_assignments')
    op.drop_table('caregiver_assignments')
    op.drop_index(op.f('ix_care_plans_id'), table_name='care_plans')
    op.drop_table('care_plans')
    op.drop_index(op.f('ix_appointments_id'), table_name='appointments')
    op.drop_table('appointments')
    op.drop_index(op.f('ix_accessibility_logs_id'), table_name='accessibility_logs')
    op.drop_table('accessibility_logs')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_emergency_response_plans_id'), table_name='emergency_response_plans')
    op.drop_table('emergency_response_plans')
    op.drop_index(op.f('ix_traditional_medicines_id'), table_name='traditional_medicines')
    op.drop_table('traditional_medicines')
    op.drop_table('support_groups')
    op.drop_index(op.f('ix_subscription_plans_id'), table_name='subscription_plans')
    op.drop_table('subscription_plans')
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_national_emergency_resources_id'), table_name='national_emergency_resources')
    op.drop_table('national_emergency_resources')
    op.drop_index(op.f('ix_mental_health_resources_id'), table_name='mental_health_resources')
    op.drop_table('mental_health_resources')
    op.drop_index(op.f('ix_emergency_resources_id'), table_name='emergency_resources')
    op.drop_table('emergency_resources')
    op.drop_index(op.f('ix_emergency_regions_id'), table_name='emergency_regions')
    op.drop_table('emergency_regions')
    op.drop_index(op.f('ix_emergency_protocols_id'), table_name='emergency_protocols')
    op.drop_table('emergency_protocols')
    op.drop_index(op.f('ix_emergency_alerts_id'), table_name='emergency_alerts')
    op.drop_table('emergency_alerts')
    op.drop_index(op.f('ix_cultural_health_resources_id'), table_name='cultural_health_resources')
    op.drop_table('cultural_health_resources')
    op.drop_index(op.f('ix_content_translations_id'), table_name='content_translations')
    op.drop_table('content_translations')
    # ### end Alembic commands ###
