"""added new tables

Revision ID: ceaf10b758f4
Revises: c7e50711d83a
Create Date: 2025-05-19 23:42:40.047737

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ceaf10b758f4'
down_revision: Union[str, None] = 'c7e50711d83a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    # --- Fix for the casting error ---
    emergency_status_enum = sa.Enum(
        'INITIALIZED', 'DISPATCHED', 'IN_PROGRESS', 'RESOLVED', 'CANCELLED',
        name='emergencystatus'
    )
    emergency_status_enum.create(op.get_bind(), checkfirst=True)

    op.execute("""
    DO $$
    BEGIN
        IF EXISTS (
            SELECT 1 FROM emergency_responses
            WHERE status NOT IN ('INITIALIZED', 'DISPATCHED', 'IN_PROGRESS', 'RESOLVED', 'CANCELLED')
        ) THEN
            RAISE EXCEPTION 'Invalid status value found in emergency_responses table.';
        END IF;
    END$$;
    """)

    op.execute("""
    ALTER TABLE emergency_responses
    ALTER COLUMN status TYPE emergencystatus
    USING status::emergencystatus;
    """)

    # Continue with rest of the schema operations
    # Avoid duplicate column error
from sqlalchemy import inspect

conn = op.get_bind()
inspector = inspect(conn)
columns = [col["name"] for col in inspector.get_columns("users")]

if "updated_at" not in columns:
    op.add_column('users', sa.Column('updated_at', sa.DateTime(), nullable=True))

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('community_guidelines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('rules', sa.JSON(), nullable=False),
    sa.Column('enforcement_policy', sa.JSON(), nullable=False),
    sa.Column('examples', sa.JSON(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('applicable_content_types', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_community_guidelines_id'), 'community_guidelines', ['id'], unique=False)
    op.create_table('content_filters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filter_type', sa.String(), nullable=False),
    sa.Column('filter_pattern', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('action', sa.Enum('WARNING', 'CONTENT_REMOVAL', 'TEMPORARY_SUSPENSION', 'PERMANENT_BAN', 'CONTENT_FLAGGING', 'CONTENT_EDIT', name='moderationaction'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_filters_id'), 'content_filters', ['id'], unique=False)
    op.create_table('emergency_zones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('center_lat', sa.Float(), nullable=True),
    sa.Column('center_lon', sa.Float(), nullable=True),
    sa.Column('radius_km', sa.Float(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('active_emergencies', sa.Integer(), nullable=True),
    sa.Column('protocol', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emergency_zones_id'), 'emergency_zones', ['id'], unique=False)
    op.create_table('medical_terms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('language_code', sa.String(length=10), nullable=False),
    sa.Column('language_variant', sa.String(length=10), nullable=True),
    sa.Column('term', sa.Text(), nullable=False),
    sa.Column('translation', sa.Text(), nullable=False),
    sa.Column('transliteration', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category', 'language_code', 'language_variant', 'term', name='uix_medical_term')
    )
    op.create_index(op.f('ix_medical_terms_id'), 'medical_terms', ['id'], unique=False)
    op.create_table('moderation_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('period_start', sa.DateTime(), nullable=False),
    sa.Column('period_end', sa.DateTime(), nullable=False),
    sa.Column('total_content_analyzed', sa.Integer(), nullable=False),
    sa.Column('total_violations', sa.Integer(), nullable=False),
    sa.Column('violation_types', sa.JSON(), nullable=False),
    sa.Column('action_distribution', sa.JSON(), nullable=False),
    sa.Column('average_response_time', sa.Float(), nullable=False),
    sa.Column('user_satisfaction_score', sa.Float(), nullable=False),
    sa.Column('moderation_efficiency', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_moderation_metrics_id'), 'moderation_metrics', ['id'], unique=False)
    op.create_table('content_analysis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content_id', sa.Integer(), nullable=False),
    sa.Column('content_type', sa.Enum('POST', 'COMMENT', 'MESSAGE', 'PROFILE', 'GROUP', name='contenttype'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('violations', sa.JSON(), nullable=False),
    sa.Column('risk_level', sa.String(), nullable=False),
    sa.Column('recommended_actions', sa.JSON(), nullable=False),
    sa.Column('analysis_timestamp', sa.DateTime(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('context_notes', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_analysis_id'), 'content_analysis', ['id'], unique=False)
    op.create_table('emergency_teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('leader_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['leader_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emergency_teams_id'), 'emergency_teams', ['id'], unique=False)
    op.create_table('guideline_enforcement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content_id', sa.Integer(), nullable=False),
    sa.Column('content_type', sa.Enum('POST', 'COMMENT', 'MESSAGE', 'PROFILE', 'GROUP', name='contenttype'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('violation_type', sa.Enum('INAPPROPRIATE_LANGUAGE', 'HARASSMENT', 'SPAM', 'HATE_SPEECH', 'MISINFORMATION', 'PRIVACY_VIOLATION', 'OTHER', name='violationtype'), nullable=False),
    sa.Column('action_taken', sa.Enum('WARNING', 'CONTENT_REMOVAL', 'TEMPORARY_SUSPENSION', 'PERMANENT_BAN', 'CONTENT_FLAGGING', 'CONTENT_EDIT', name='moderationaction'), nullable=False),
    sa.Column('action_timestamp', sa.DateTime(), nullable=True),
    sa.Column('moderator_id', sa.Integer(), nullable=False),
    sa.Column('enforcement_notes', sa.String(), nullable=True),
    sa.Column('appeal_status', sa.String(), nullable=True),
    sa.Column('appeal_deadline', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['moderator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_guideline_enforcement_id'), 'guideline_enforcement', ['id'], unique=False)
    op.create_table('moderation_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reporter_id', sa.Integer(), nullable=False),
    sa.Column('reported_content_id', sa.Integer(), nullable=False),
    sa.Column('reported_content_type', sa.Enum('POST', 'COMMENT', 'MESSAGE', 'PROFILE', 'GROUP', name='contenttype'), nullable=False),
    sa.Column('reported_user_id', sa.Integer(), nullable=False),
    sa.Column('violation_type', sa.Enum('INAPPROPRIATE_LANGUAGE', 'HARASSMENT', 'SPAM', 'HATE_SPEECH', 'MISINFORMATION', 'PRIVACY_VIOLATION', 'OTHER', name='violationtype'), nullable=False),
    sa.Column('report_reason', sa.String(), nullable=False),
    sa.Column('report_timestamp', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('resolution', sa.String(), nullable=True),
    sa.Column('resolution_timestamp', sa.DateTime(), nullable=True),
    sa.Column('moderator_notes', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['reported_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['reporter_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_moderation_reports_id'), 'moderation_reports', ['id'], unique=False)
    op.create_table('user_moderation_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('total_violations', sa.Integer(), nullable=False),
    sa.Column('current_status', sa.String(), nullable=False),
    sa.Column('warning_count', sa.Integer(), nullable=False),
    sa.Column('suspension_count', sa.Integer(), nullable=False),
    sa.Column('last_violation_date', sa.DateTime(), nullable=True),
    sa.Column('improvement_notes', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_moderation_history_id'), 'user_moderation_history', ['id'], unique=False)
    op.create_table('voice_commands',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('command', sa.Text(), nullable=False),
    sa.Column('intent', sa.String(length=50), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=True),
    sa.Column('confidence', sa.Integer(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_voice_commands_id'), 'voice_commands', ['id'], unique=False)
    op.create_table('care_plan_diets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('care_plan_id', sa.Integer(), nullable=False),
    sa.Column('meal_type', sa.String(), nullable=False),
    sa.Column('time', sa.String(), nullable=False),
    sa.Column('food_items', sa.JSON(), nullable=False),
    sa.Column('portion_sizes', sa.JSON(), nullable=True),
    sa.Column('nutritional_info', sa.JSON(), nullable=True),
    sa.Column('alternatives', sa.JSON(), nullable=True),
    sa.Column('restrictions', sa.JSON(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['care_plan_id'], ['care_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_care_plan_diets_id'), 'care_plan_diets', ['id'], unique=False)
    op.create_table('care_plan_exercises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('care_plan_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('frequency', sa.String(), nullable=False),
    sa.Column('intensity_level', sa.String(), nullable=True),
    sa.Column('equipment_needed', sa.JSON(), nullable=True),
    sa.Column('video_url', sa.String(), nullable=True),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('precautions', sa.Text(), nullable=True),
    sa.Column('target_muscle_groups', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['care_plan_id'], ['care_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_care_plan_exercises_id'), 'care_plan_exercises', ['id'], unique=False)
    op.create_table('care_plan_treatments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('care_plan_id', sa.Integer(), nullable=False),
    sa.Column('diagnosis', sa.Text(), nullable=False),
    sa.Column('goals', sa.JSON(), nullable=False),
    sa.Column('medications', sa.JSON(), nullable=True),
    sa.Column('lifestyle_changes', sa.JSON(), nullable=True),
    sa.Column('follow_up_schedule', sa.JSON(), nullable=True),
    sa.Column('risk_factors', sa.JSON(), nullable=True),
    sa.Column('emergency_contacts', sa.JSON(), nullable=True),
    sa.Column('progress_metrics', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['care_plan_id'], ['care_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_care_plan_treatments_id'), 'care_plan_treatments', ['id'], unique=False)
    op.create_table('emergency_tracking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('emergency_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('location_lat', sa.Float(), nullable=True),
    sa.Column('location_lon', sa.Float(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('meta_data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['emergency_id'], ['emergency_responses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emergency_tracking_id'), 'emergency_tracking', ['id'], unique=False)
    op.create_table('referral_system',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('from_practitioner_id', sa.Integer(), nullable=True),
    sa.Column('to_practitioner_id', sa.Integer(), nullable=True),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['from_practitioner_id'], ['practitioners.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['to_practitioner_id'], ['practitioners.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_referral_system_id'), 'referral_system', ['id'], unique=False)
    op.create_table('team_members',
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['emergency_teams.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    op.create_table('emergency_dispatches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('emergency_id', sa.Integer(), nullable=True),
    sa.Column('resource_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('dispatch_time', sa.DateTime(), nullable=True),
    sa.Column('arrival_time', sa.DateTime(), nullable=True),
    sa.Column('completion_time', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['emergency_id'], ['emergency_responses.id'], ),
    sa.ForeignKeyConstraint(['resource_id'], ['emergency_resources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emergency_dispatches_id'), 'emergency_dispatches', ['id'], unique=False)
    op.create_table('emergency_resource_inventory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=True),
    sa.Column('item_type', sa.String(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('last_restocked', sa.DateTime(), nullable=True),
    sa.Column('minimum_quantity', sa.Integer(), nullable=True),
    sa.Column('maximum_quantity', sa.Integer(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['resource_id'], ['emergency_resources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emergency_resource_inventory_id'), 'emergency_resource_inventory', ['id'], unique=False)
    op.add_column('accessibility_logs', sa.Column('meta_data', sa.JSON(), nullable=True))
    op.add_column('accessibility_logs', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.alter_column('accessibility_logs', 'success',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_column('accessibility_logs', 'timestamp')
    op.drop_column('accessibility_logs', 'error_message')
    op.drop_column('accessibility_logs', 'access_log_metadata')
    op.drop_column('care_plans', 'exercises')
    op.add_column('content_translations', sa.Column('user_id', sa.Integer(), nullable=False))
    op.add_column('content_translations', sa.Column('original_text', sa.Text(), nullable=False))
    op.add_column('content_translations', sa.Column('source_language', sa.String(length=10), nullable=False))
    op.add_column('content_translations', sa.Column('target_language', sa.String(length=10), nullable=False))
    op.add_column('content_translations', sa.Column('language_variant', sa.String(length=10), nullable=True))
    op.add_column('content_translations', sa.Column('medical_terms', sa.JSON(), nullable=True))
    op.alter_column('content_translations', 'translated_text',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('content_translations', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=True)
    op.create_foreign_key(None, 'content_translations', 'users', ['user_id'], ['id'])
    op.drop_column('content_translations', 'content_type')
    op.drop_column('content_translations', 'content_key')
    op.drop_column('content_translations', 'language_code')
    op.drop_column('content_translations', 'updated_at')
    op.drop_column('content_translations', 'context')
    op.alter_column('ehr_connections', 'ehr_system',
               existing_type=postgresql.ENUM('EPIC', 'CERNER', 'MY_HEALTH_RECORD', 'NATIONAL_IMMUNIZATION', 'NATIONAL_PRESCRIPTION', 'NATIONAL_HEALTH_ID', 'CUSTOM', name='ehrsystem'),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('ehr_connections', 'connection_config',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.drop_column('ehr_connections', 'last_sync')
    op.add_column('emergency_resources', sa.Column('capability_score', sa.Float(), nullable=True))
    op.add_column('emergency_resources', sa.Column('assigned_user_id', sa.Integer(), nullable=True))
    op.add_column('emergency_resources', sa.Column('current_emergency_id', sa.Integer(), nullable=True))
    op.add_column('emergency_resources', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('emergency_resources', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'emergency_resources', 'users', ['assigned_user_id'], ['id'])
    op.create_foreign_key(None, 'emergency_resources', 'emergency_responses', ['current_emergency_id'], ['id'])
    op.add_column('emergency_responses', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('emergency_responses', sa.Column('dispatched_at', sa.DateTime(), nullable=True))
    op.add_column('emergency_responses', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # Ensure enum exists
    emergency_status_enum = sa.Enum(
    'INITIALIZED', 'DISPATCHED', 'IN_PROGRESS', 'RESOLVED', 'CANCELLED',
    name='emergencystatus'
)
    emergency_status_enum.create(op.get_bind(), checkfirst=True)

# Ensure all data in `status` column is valid (optional but safe)
    op.execute("""
    DO $$ BEGIN
        IF EXISTS (
            SELECT 1 FROM emergency_responses
            WHERE status NOT IN ('INITIALIZED', 'DISPATCHED', 'IN_PROGRESS', 'RESOLVED', 'CANCELLED')
        ) THEN
            RAISE EXCEPTION 'Invalid status found in emergency_responses';
        END IF;
    END$$;
""")

# Safely cast existing column to enum
    op.execute("""
    ALTER TABLE emergency_responses
    ALTER COLUMN status
    TYPE emergencystatus
    USING status::emergencystatus;
""")

    op.drop_column('emergency_responses', 'reported_at')
    op.alter_column('national_database_connections', 'database_type',
               existing_type=postgresql.ENUM('MY_HEALTH_RECORD', 'IMMUNIZATION_REGISTRY', 'PRESCRIPTION_DATABASE', 'HEALTH_IDENTIFIER', 'MEDICARE', 'MEDICAID', name='nationaldatabasetype'),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('national_database_connections', 'access_token',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('national_database_connections', 'connection_config',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.drop_column('national_database_connections', 'last_sync')
    op.add_column('user_accessibility', sa.Column('language_variant', sa.String(length=10), nullable=True))
    op.add_column('user_accessibility', sa.Column('voice_enabled', sa.Boolean(), nullable=True))
    op.add_column('user_accessibility', sa.Column('voice_language', sa.String(length=10), nullable=True))
    op.add_column('user_accessibility', sa.Column('voice_speed', sa.Integer(), nullable=True))
    op.add_column('user_accessibility', sa.Column('text_size', sa.Integer(), nullable=True))
    op.add_column('user_accessibility', sa.Column('high_contrast', sa.Boolean(), nullable=True))
    op.add_column('user_accessibility', sa.Column('screen_reader', sa.Boolean(), nullable=True))
    op.alter_column('user_accessibility', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=True)
    op.alter_column('user_accessibility', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=True)
    op.drop_constraint('user_accessibility_user_id_key', 'user_accessibility', type_='unique')
    op.drop_column('user_accessibility', 'voice_input_enabled')
    op.drop_column('user_accessibility', 'secondary_languages')
    op.drop_column('user_accessibility', 'font_size')
    op.drop_column('user_accessibility', 'high_contrast_mode')
    op.drop_column('user_accessibility', 'screen_reader_enabled')
    op.drop_column('user_accessibility', 'preferred_voice')
    op.drop_column('user_accessibility', 'voice_output_enabled')
    op.drop_column('user_accessibility', 'reduced_motion')
    from sqlalchemy import inspect

conn = op.get_bind()
inspector = inspect(conn)

if 'updated_at' not in [col['name'] for col in inspector.get_columns('users')]:
    op.add_column('users', sa.Column('updated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""

    # Safely revert enum change
    op.execute("""
    ALTER TABLE emergency_responses
    ALTER COLUMN status TYPE VARCHAR;
    """)

    emergency_status_enum = sa.Enum(
        'INITIALIZED', 'DISPATCHED', 'IN_PROGRESS', 'RESOLVED', 'CANCELLED',
        name='emergencystatus'
    )
    emergency_status_enum.drop(op.get_bind(), checkfirst=True)

    op.drop_column('users', 'updated_at')
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'updated_at')
    op.add_column('user_accessibility', sa.Column('reduced_motion', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('user_accessibility', sa.Column('voice_output_enabled', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('user_accessibility', sa.Column('preferred_voice', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('user_accessibility', sa.Column('screen_reader_enabled', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('user_accessibility', sa.Column('high_contrast_mode', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('user_accessibility', sa.Column('font_size', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('user_accessibility', sa.Column('secondary_languages', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('user_accessibility', sa.Column('voice_input_enabled', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.create_unique_constraint('user_accessibility_user_id_key', 'user_accessibility', ['user_id'])
    op.alter_column('user_accessibility', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('user_accessibility', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_column('user_accessibility', 'screen_reader')
    op.drop_column('user_accessibility', 'high_contrast')
    op.drop_column('user_accessibility', 'text_size')
    op.drop_column('user_accessibility', 'voice_speed')
    op.drop_column('user_accessibility', 'voice_language')
    op.drop_column('user_accessibility', 'voice_enabled')
    op.drop_column('user_accessibility', 'language_variant')
    op.add_column('national_database_connections', sa.Column('last_sync', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.alter_column('national_database_connections', 'connection_config',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('national_database_connections', 'access_token',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('national_database_connections', 'database_type',
               existing_type=sa.String(),
               type_=postgresql.ENUM('MY_HEALTH_RECORD', 'IMMUNIZATION_REGISTRY', 'PRESCRIPTION_DATABASE', 'HEALTH_IDENTIFIER', 'MEDICARE', 'MEDICAID', name='nationaldatabasetype'),
               existing_nullable=False)
    op.add_column('emergency_responses', sa.Column('reported_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.alter_column('emergency_responses', 'status',
               existing_type=sa.Enum('INITIALIZED', 'DISPATCHED', 'IN_PROGRESS', 'RESOLVED', 'CANCELLED', name='emergencystatus'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_column('emergency_responses', 'updated_at')
    op.drop_column('emergency_responses', 'dispatched_at')
    op.drop_column('emergency_responses', 'created_at')
    op.drop_constraint(None, 'emergency_resources', type_='foreignkey')
    op.drop_constraint(None, 'emergency_resources', type_='foreignkey')
    op.drop_column('emergency_resources', 'updated_at')
    op.drop_column('emergency_resources', 'created_at')
    op.drop_column('emergency_resources', 'current_emergency_id')
    op.drop_column('emergency_resources', 'assigned_user_id')
    op.drop_column('emergency_resources', 'capability_score')
    op.add_column('ehr_connections', sa.Column('last_sync', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.alter_column('ehr_connections', 'connection_config',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('ehr_connections', 'ehr_system',
               existing_type=sa.String(),
               type_=postgresql.ENUM('EPIC', 'CERNER', 'MY_HEALTH_RECORD', 'NATIONAL_IMMUNIZATION', 'NATIONAL_PRESCRIPTION', 'NATIONAL_HEALTH_ID', 'CUSTOM', name='ehrsystem'),
               existing_nullable=False)
    op.add_column('content_translations', sa.Column('context', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('content_translations', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('content_translations', sa.Column('language_code', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('content_translations', sa.Column('content_key', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('content_translations', sa.Column('content_type', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'content_translations', type_='foreignkey')
    op.alter_column('content_translations', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('content_translations', 'translated_text',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_column('content_translations', 'medical_terms')
    op.drop_column('content_translations', 'language_variant')
    op.drop_column('content_translations', 'target_language')
    op.drop_column('content_translations', 'source_language')
    op.drop_column('content_translations', 'original_text')
    op.drop_column('content_translations', 'user_id')
    op.add_column('care_plans', sa.Column('exercises', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('accessibility_logs', sa.Column('access_log_metadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('accessibility_logs', sa.Column('error_message', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('accessibility_logs', sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.alter_column('accessibility_logs', 'success',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_column('accessibility_logs', 'created_at')
    op.drop_column('accessibility_logs', 'meta_data')
    op.drop_index(op.f('ix_emergency_resource_inventory_id'), table_name='emergency_resource_inventory')
    op.drop_table('emergency_resource_inventory')
    op.drop_index(op.f('ix_emergency_dispatches_id'), table_name='emergency_dispatches')
    op.drop_table('emergency_dispatches')
    op.drop_table('team_members')
    op.drop_index(op.f('ix_referral_system_id'), table_name='referral_system')
    op.drop_table('referral_system')
    op.drop_index(op.f('ix_emergency_tracking_id'), table_name='emergency_tracking')
    op.drop_table('emergency_tracking')
    op.drop_index(op.f('ix_care_plan_treatments_id'), table_name='care_plan_treatments')
    op.drop_table('care_plan_treatments')
    op.drop_index(op.f('ix_care_plan_exercises_id'), table_name='care_plan_exercises')
    op.drop_table('care_plan_exercises')
    op.drop_index(op.f('ix_care_plan_diets_id'), table_name='care_plan_diets')
    op.drop_table('care_plan_diets')
    op.drop_index(op.f('ix_voice_commands_id'), table_name='voice_commands')
    op.drop_table('voice_commands')
    op.drop_index(op.f('ix_user_moderation_history_id'), table_name='user_moderation_history')
    op.drop_table('user_moderation_history')
    op.drop_index(op.f('ix_moderation_reports_id'), table_name='moderation_reports')
    op.drop_table('moderation_reports')
    op.drop_index(op.f('ix_guideline_enforcement_id'), table_name='guideline_enforcement')
    op.drop_table('guideline_enforcement')
    op.drop_index(op.f('ix_emergency_teams_id'), table_name='emergency_teams')
    op.drop_table('emergency_teams')
    op.drop_index(op.f('ix_content_analysis_id'), table_name='content_analysis')
    op.drop_table('content_analysis')
    op.drop_index(op.f('ix_moderation_metrics_id'), table_name='moderation_metrics')
    op.drop_table('moderation_metrics')
    op.drop_index(op.f('ix_medical_terms_id'), table_name='medical_terms')
    op.drop_table('medical_terms')
    op.drop_index(op.f('ix_emergency_zones_id'), table_name='emergency_zones')
    op.drop_table('emergency_zones')
    op.drop_index(op.f('ix_content_filters_id'), table_name='content_filters')
    op.drop_table('content_filters')
    op.drop_index(op.f('ix_community_guidelines_id'), table_name='community_guidelines')
    op.drop_table('community_guidelines')
    # ### end Alembic commands ###
