"""changes in user table

Revision ID: dc446e210556
Revises: 8a06306e1d5c
Create Date: 2025-05-26 22:22:12.456780

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dc446e210556'
down_revision: Union[str, None] = '8a06306e1d5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop tables with dependencies first
    op.drop_index('ix_indigenous_health_support_requests_id', table_name='indigenous_health_support_requests')
    op.drop_table('indigenous_health_support_requests')
    
    # Now drop the tables that were depended upon
    op.drop_index('ix_health_predictions_id', table_name='health_predictions')
    op.drop_table('health_predictions')
    op.drop_index('ix_indigenous_health_profiles_id', table_name='indigenous_health_profiles')
    op.drop_table('indigenous_health_profiles')
    op.drop_index('ix_health_trends_id', table_name='health_trends')
    op.drop_table('health_trends')
    op.drop_index('ix_health_risk_factors_id', table_name='health_risk_factors')
    op.drop_table('health_risk_factors')
    op.drop_index('ix_health_insights_id', table_name='health_insights')
    op.drop_table('health_insights')
    op.drop_index('ix_cultural_health_resources_id', table_name='cultural_health_resources')
    op.drop_table('cultural_health_resources')
    op.drop_index('ix_traditional_medicines_id', table_name='traditional_medicines')
    op.drop_table('traditional_medicines')
    
    # Update NULL date_of_birth values to a default date before making it non-nullable
    op.execute("UPDATE users SET date_of_birth = '2000-01-01' WHERE date_of_birth IS NULL")
    
    # Change date_of_birth column type from TIMESTAMP to DATE
    op.execute("ALTER TABLE users ALTER COLUMN date_of_birth TYPE DATE USING date_of_birth::DATE")
    
    # Now make the column non-nullable
    op.alter_column('users', 'date_of_birth',
               existing_type=postgresql.DATE(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'date_of_birth',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.create_table('traditional_medicines',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('community', postgresql.ENUM('FIRST_NATIONS', 'INUIT', 'METIS', 'ABORIGINAL', 'TORRES_STRAIT', 'OTHER', name='indigenouscommunity'), autoincrement=False, nullable=False),
    sa.Column('uses', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('preparation_method', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('dosage_guidelines', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('contraindications', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('cultural_context', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_verified', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='traditional_medicines_pkey')
    )
    op.create_index('ix_traditional_medicines_id', 'traditional_medicines', ['id'], unique=False)
    op.create_table('cultural_health_resources',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('contact', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('community', postgresql.ENUM('FIRST_NATIONS', 'INUIT', 'METIS', 'ABORIGINAL', 'TORRES_STRAIT', 'OTHER', name='indigenouscommunity'), autoincrement=False, nullable=False),
    sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('services_offered', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('cultural_specificity', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('accessibility_notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='cultural_health_resources_pkey')
    )
    op.create_index('ix_cultural_health_resources_id', 'cultural_health_resources', ['id'], unique=False)
    op.create_table('health_insights',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('insight_type', postgresql.ENUM('SYMPTOM_ANALYSIS', 'TREND_PREDICTION', 'RISK_ASSESSMENT', 'LIFESTYLE_INSIGHT', 'MEDICATION_INSIGHT', 'MENTAL_HEALTH', 'CHRONIC_CONDITION', name='insighttype'), autoincrement=False, nullable=False),
    sa.Column('generated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('insight_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('summary', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('confidence_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('is_actionable', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('action_taken', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('action_taken_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('feedback_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='health_insights_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='health_insights_pkey')
    )
    op.create_index('ix_health_insights_id', 'health_insights', ['id'], unique=False)
    op.create_table('health_risk_factors',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('risk_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('risk_level', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('identified_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('contributing_factors', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('mitigation_strategies', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('last_assessed', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('assessment_frequency', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='health_risk_factors_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='health_risk_factors_pkey')
    )
    op.create_index('ix_health_risk_factors_id', 'health_risk_factors', ['id'], unique=False)
    op.create_table('indigenous_health_support_requests',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('profile_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('support_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('cultural_context', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('specific_needs', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('emergency', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('response', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['indigenous_health_profiles.id'], name='indigenous_health_support_requests_profile_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='indigenous_health_support_requests_pkey')
    )
    op.create_index('ix_indigenous_health_support_requests_id', 'indigenous_health_support_requests', ['id'], unique=False)
    op.create_table('health_trends',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('trend_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('start_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('end_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('trend_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('significance_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('impact_level', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('recommendations', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('is_monitored', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('last_updated', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='health_trends_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='health_trends_pkey')
    )
    op.create_index('ix_health_trends_id', 'health_trends', ['id'], unique=False)
    op.create_table('indigenous_health_profiles',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('community', postgresql.ENUM('FIRST_NATIONS', 'INUIT', 'METIS', 'ABORIGINAL', 'TORRES_STRAIT', 'OTHER', name='indigenouscommunity'), autoincrement=False, nullable=False),
    sa.Column('cultural_practices', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('traditional_medicines', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('health_resources', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('cultural_preferences', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('traditional_healing_consent', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('cultural_support_network', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('last_updated', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='indigenous_health_profiles_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='indigenous_health_profiles_pkey')
    )
    op.create_index('ix_indigenous_health_profiles_id', 'indigenous_health_profiles', ['id'], unique=False)
    op.create_table('health_predictions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('prediction_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('predicted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('prediction_window', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('prediction_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('confidence', postgresql.ENUM('LOW', 'MEDIUM', 'HIGH', name='predictionconfidence'), autoincrement=False, nullable=False),
    sa.Column('accuracy_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('occurred', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('occurred_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='health_predictions_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='health_predictions_pkey')
    )
    op.create_index('ix_health_predictions_id', 'health_predictions', ['id'], unique=False)
    # ### end Alembic commands ###
