"""update_all_datetime_columns_to_timezone_naive

Revision ID: f336a7e362e3
Revises: 6bfc17d6309e
Create Date: 2025-05-22 05:52:06.990481

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f336a7e362e3'
down_revision: Union[str, None] = '6bfc17d6309e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
