"""Add frequency and priority fields to care_plans table

Revision ID: faf9233facf3
Revises: 81dda835705a
Create Date: 2025-05-21 23:41:23.717424

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'faf9233facf3'
down_revision: Union[str, None] = '81dda835705a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('care_plans', sa.Column('frequency', sa.String(), nullable=False))
    op.add_column('care_plans', sa.Column('priority', sa.String(), nullable=False))
    op.add_column('care_plans', sa.Column('notes', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('care_plans', 'notes')
    op.drop_column('care_plans', 'priority')
    op.drop_column('care_plans', 'frequency')
    # ### end Alembic commands ###
